### ISSUE TITLE
Support for overriding SSH private key when connecting to the remote OCI node

### ISSUE THREAD

**Issue by dbaboy** [stephenpearson/kitchen-oci#47]
Came across this issue when we have separate ECDSA SSH key. The GEM allows the public key to be overriden using `ssh_keypath`. But, I cannot seem to find a way to override the SSH private key - corresponding to the public key. Can you please advice if there is already a way of doing this. If not, is this something that can be added. 

Presently, the work around is
- Update the YAML file for the Suite to have the hostname
- Update /etc/hosts to have a mapping for the hostname to IP
- Add a section in SSH config file to specify the SSH private key details

```
Host ktnvm*
  AddKeysToAgent yes
  IdentitiesOnly=yes
  IdentityFile ~/.ssh/id_ecdsa_myuser
  PreferredAuthentications publickey,password
  User myuser
```

**Comment by justintsteele** [comment]
i think modifying your local ssh config is really the only way to do this since.  Although it should be noted that `kitchen-oci` stores the "server_id" as the IP address of the node rather than storing the fqdn or the hostname,  so you might have to set a `Host` section in your ssh config file that calls out a portion of the IP address for the nodes you are creating.  As far as the kitchen driver is concerned, all it really needs is a public key to put on the instance so it can authenticate.  there's really nowhere that the location or contents of the private key are required.  By the time you are having issues connecting, test kitchen has passed things off to the transport module so it's more or less out of the driver's hands.
